name: release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore BatterMouse/BatterMouse.csproj

      - name: Publish
        run: dotnet publish BatterMouse/BatterMouse.csproj -c Release --no-restore -o publish/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: publish/BatterMouse.exe
